language: python

# needed to use trusty
sudo: required

dist: xenial

python:
  - "2.7"
  - "3.6"

install:
  - pip install coverage
  - python setup.py install

script:
  - coverage run setup.py test

after_success:
  - pip install coveralls && coveralls
  - pip install codecov && codecov
