# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
version: 2

shared: &shared
    working_directory: ~/repo
    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            sudo apt-get install -y dbus libdbus-1-dev libdbus-glib-1-dev
            sudo apt-get install python3-venv  # Necessary on py2.7 circleci image
            python3 -m venv venv
            . venv/bin/activate
            pip install tox
            pip install codecov

      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            # If we don't specify the python version then the default
            # 3.5 version that is part of all images is run which causes
            # issues.
            TOX_ENV="$(echo ${PYTHON_VERSION} | sed -E 's/([[:digit:]]).([[:digit:]])+.([[:digit:]])+/py\1\2/')"
            tox -e "$TOX_ENV"
            codecov

jobs:
  py2.7:
    <<: *shared
    docker:
      - image: circleci/python:2.7
  py3.4:
    <<: *shared
    docker:
      - image: circleci/python:3.4
  py3.5:
    <<: *shared
    docker:
      - image: circleci/python:3.5
  py3.6:
    <<: *shared
    docker:
      - image: circleci/python:3.6
  py3.7:
    <<: *shared
    docker:
      - image: circleci/python:3.7

workflows:
  version: 2
  test:
    jobs:
      - py2.7
      - py3.4
      - py3.5
      - py3.6
      - py3.7
